services:
  server:
    build:
      context: .
      dockerfile: MyBCA.Server/Dockerfile
    container_name: mybca-server
    environment:
      - SERVER_APP_PORT=${SERVER_APP_PORT:-8080}
      - TZ=${TZ:-America/New_York}
    ports:
      - "${SERVER_APP_PORT}:8080"
    expose:
      - "5050"
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      - TZ=${TZ:-}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    expose:
      - "9090"
    networks:
      - monitoring
    depends_on:
      - server
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - TZ=${TZ:-}
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: