services:
  webapp:
    build: .
    container_name: mybca-server
    environment:
      - SERVER_APP_PORT=${SERVER_APP_PORT:-8080}
      - SERVER_PROMETHEUS_PORT=${SERVER_PROMETHEUS_PORT:-8081}
      - BUS_SHEET_URL=${BUS_SHEET_URL:-}
      - NUTRISLICE_API_URL=${NUTRISLICE_API_URL:-}
      - TZ=${TZ:-}
    ports:
      - "${SERVER_APP_PORT}:${SERVER_APP_PORT}" # keep this exposed for public access
    expose:
      - "${SERVER_PROMETHEUS_PORT}" # only visible to Prometheus inside the network
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      - TZ=${TZ:-}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    expose:
      - "9090" # available only inside Docker network
    networks:
      - monitoring
    depends_on:
      - webapp

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000" # expose Grafana to host
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - TZ=${TZ:-}
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: